# Bronze Layer - Data Understanding (Raw Layer)

## Objective
The Bronze layer is responsible for ingesting the raw Bitcoin datasets from the source without applying any cleaning or transformations. This layer preserves the original data and serves as the foundation for the remaining stages of the Medallion Architecture.

## Steps Performed
- Download the Bitcoin historical dataset from Kaggle.
- Load the four different timeframes:
  - 15 Minutes
  - 1 Hour
  - 4 Hours
  - 1 Day
- Display the first few rows of each dataset.
- Inspect the number of rows and columns.
- Review the available column names.
- Check data types.
## Output
- **Input:** Raw CSV files from Kaggle
- **Output:** "bronze_15m.csv"
              "bronze_1h.csv"
              "bronze_4h.csv"
              "bronze_1d.csv"

> **Note:** No data cleaning, preprocessing, or feature engineering is performed in the Bronze layer. The data is stored exactly as received from the source.

In [3]:
#import libraries
import pandas as pd
import numpy as np

In [4]:
#download data from kaggle
import kagglehub
path = kagglehub.dataset_download("novandraanugrah/bitcoin-historical-datasets-2018-2024")

c:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\admin\.cache\kagglehub\datasets\novandraanugrah\bitcoin-historical-datasets-2018-2024\432.archive...

100%|██████████| 20.1M/20.1M [00:16<00:00, 1.26MB/s]

Extracting files...

In [5]:
# Load raw datasets
df_15m = pd.read_csv(path + "/btc_15m_data_2018_to_2025.csv")
df_1h  = pd.read_csv(path + "/btc_1h_data_2018_to_2025.csv")
df_4h  = pd.read_csv(path + "/btc_4h_data_2018_to_2025.csv")
df_1d  = pd.read_csv(path + "/btc_1d_data_2018_to_2025.csv")

In [6]:
# Save Bronze datasets

df_15m.to_csv("bronze_15m.csv", index=False)
df_1h.to_csv("bronze_1h.csv", index=False)
df_4h.to_csv("bronze_4h.csv", index=False)
df_1d.to_csv("bronze_1d.csv", index=False)

In [7]:
#display 5 rows from 15 minutes file
print("15 Minutes")
display(df_15m.head())

15 Minutes

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00.000000,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000,1.675545e+06,1572,63.227133,8.576108e+05,0
1,2018-01-01 00:15:00.000000,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000,1.321757e+06,1461,47.686389,6.422812e+05,0
2,2018-01-01 00:30:00.000000,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000,1.078825e+06,1000,43.710406,5.900347e+05,0
3,2018-01-01 00:45:00.000000,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000,1.917783e+06,1195,73.897993,1.000614e+06,0
4,2018-01-01 01:00:00.000000,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000,9.778198e+05,898,34.257652,4.618369e+05,0

In [8]:
#display 5 rows from 1 hour file
print("1 Hour")
display(df_1h.head())

1 Hour

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00.000000,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000,5.993910e+06,5228,228.521921,3.090541e+06,0
1,2018-01-01 01:00:00.000000,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000,5.154522e+06,4534,180.840403,2.430449e+06,0
2,2018-01-01 02:00:00.000000,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000,5.710192e+06,4887,192.237935,2.558505e+06,0
3,2018-01-01 03:00:00.000000,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000,5.657448e+06,4789,137.918407,1.858041e+06,0
4,2018-01-01 04:00:00.000000,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000,4.588047e+06,4563,172.957635,2.328058e+06,0

In [9]:
#display 5 rows from 4 hours file
print("4 Hours")
display(df_4h.head())

4 Hours

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00.000000,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000,2.251607e+07,19438,739.518666,9.937537e+06,0
1,2018-01-01 04:00:00.000000,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000,1.770254e+07,18061,588.516222,7.998796e+06,0
2,2018-01-01 08:00:00.000000,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000,1.765121e+07,17200,582.668293,7.792109e+06,0
3,2018-01-01 12:00:00.000000,13220.56,13330.00,12750.00,13247.00,1831.933153,2018-01-01 15:59:59.999000,2.391259e+07,21357,830.314747,1.083304e+07,0
4,2018-01-01 16:00:00.000000,13247.00,13290.65,12940.00,13240.37,1092.337234,2018-01-01 19:59:59.999000,1.434887e+07,13178,557.453779,7.324320e+06,0

In [10]:
#display 5 rows from 1 day file
print("1 Day")
display(df_1d.head())

1 Day

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00.000000 UTC,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000 UTC,1.147997e+08,105595,3961.938946,5.280975e+07,0
1,2018-01-02 00:00:00.000000 UTC,13382.16,15473.49,12890.02,14675.11,20078.092111,2018-01-02 23:59:59.999000 UTC,2.797171e+08,177728,11346.326739,1.580801e+08,0
2,2018-01-03 00:00:00.000000 UTC,14690.00,15307.56,14150.00,14919.51,15905.667639,2018-01-03 23:59:59.999000 UTC,2.361169e+08,162787,8994.953566,1.335873e+08,0
3,2018-01-04 00:00:00.000000 UTC,14919.51,15280.00,13918.04,15059.54,21329.649574,2018-01-04 23:59:59.999000 UTC,3.127816e+08,170310,12680.812951,1.861168e+08,0
4,2018-01-05 00:00:00.000000 UTC,15059.56,17176.24,14600.00,16960.39,23251.491125,2018-01-05 23:59:59.999000 UTC,3.693220e+08,192969,13346.622293,2.118299e+08,0

In [11]:
print(df_15m.shape)
print(df_1h.shape)
print(df_4h.shape)
print(df_1d.shape)

(295917, 12)
(73991, 12)
(18513, 12)
(3089, 12)

In [12]:
df_15m.columns

Index(['Open time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Close time',
       'Quote asset volume', 'Number of trades', 'Taker buy base asset volume',
       'Taker buy quote asset volume', 'Ignore'],
      dtype='object')

In [13]:
df_15m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295917 entries, 0 to 295916
Data columns (total 12 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Open time                     295916 non-null  object
 1   Open                          295917 non-null  float64
 2   High                          295917 non-null  float64
 3   Low                           295917 non-null  float64
 4   Close                         295917 non-null  float64
 5   Volume                        295917 non-null  float64
 6   Close time                    295916 non-null  object
 7   Quote asset volume            295917 non-null  float64
 8   Number of trades              295917 non-null  int64
 9   Taker buy base asset volume   295917 non-null  float64
 10  Taker buy quote asset volume  295917 non-null  float64
 11  Ignore                        295917 non-null  int64
dtypes: float64(8), int64(2), object(2)
memory usage: 27.1+ MB